---
branches:
  only:
    - master
    - /^v/
language: python
python: 3.6
os: linux

env:
  global:
    - ROLE_NAME=ivansible.srv_cgpro
    - IVATEST_SSH_SERVER=true
    - IVATEST_SYSTEMD_TMPFILES=true

before_install:
  - ln -s $TRAVIS_BUILD_DIR $(dirname $TRAVIS_BUILD_DIR)/$ROLE_NAME

install:
  - pip3 install -U pip setuptools wheel
  - pip3 install docker jmespath boto3 mitogen molecule pytest testinfra
  # also pulled: ansible-lint yamllint flake8

matrix:
  include:
    - name: test on xenial
      dist: xenial
      env:
        - IVATEST_FIREWALL=ferm
        - IVATEST_CHECK_HTTPS_HTML=false
      script:
        - molecule test -s localhost

    - name: test on bionic
      dist: bionic
      env:
        - IVATEST_FIREWALL=ferm
        - IVATEST_CHECK_HTTPS_HTML=false
      script:
        - molecule test -s localhost

    - name: tests in docker
      dist: bionic
      services: docker
      env:
        - IVATEST_FIREWALL=none
        - IVATEST_CHECK_HTTPS_HTML=true
      script:
        - molecule lint
        - molecule destroy
        - molecule dependency
        - molecule syntax
        - molecule create
        - molecule converge
        - travis_wait 30 molecule idempotence
        - molecule verify
        - molecule destroy
...
