---
- name: check that role lin_nginx is deployed
  stat:
    path: "{{ nginx_def_site_dir }}/favicon.ico"
    get_checksum: false
  register: check_nginx_site_dir

- name: deploy role lin_nginx
  # Condition for this step will be rarely true.
  # Prefer include (vs import) to avoid lots of skip messages.
  include_role:
    name: ivansible.lin_nginx
  when: not check_nginx_site_dir.stat.exists

- name: deploy custom cgpro favicon
  get_url:
    url: "{{ cgpro_favicon_url }}"
    dest: "{{ nginx_def_site_dir }}/favicon-cgpro.ico"

- name: configure cgpro webmail for nginx
  template:
    src: cgpro-mail.nginx.conf
    dest: "{{ nginx_site_dir }}/cgpro-mail.conf"
    lstrip_blocks: true
  notify: reload nginx service

- name: configure cgpro admin site for nginx
  template:
    src: cgpro-admin.nginx.conf
    dest: "{{ nginx_site_dir }}/cgpro-admin.conf"
    lstrip_blocks: true
  notify: reload nginx service
...
