---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: xenial
    image: ivandeex/molecule:16.04
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - molecule
  - name: bionic
    image: ivandeex/molecule:18.04
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - molecule
provisioner:
  name: ansible
  inventory:
    group_vars:
      molecule:
        ansible_user: ansible
        lin_core_system_locale: en_US.UTF-8
        allow_sysctl: false
        lin_use_ssh: ${IVATEST_SSH_SERVER:-true}
        lin_systemd_tmpfiles: ${IVATEST_SYSTEMD_TMPFILES:-true}
        # these will fail in docker:
        lin_firewall: ${IVATEST_FIREWALL:-ferm}
        lin_core_time_sync: false
        # settings:
        cgpro_deb_url: https://dropbox.com/s/u4s7d3p7jnquvdx/CGatePro-Linux_6.2-7_amd64.deb?dl=1
  lint:
    name: ansible-lint
verifier:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
scenario:
  name: default
  converge_sequence:
    - converge
  test_sequence:
    - lint
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
...
