---
- name: prepare
  hosts: all
  pre_tasks:
    - name: vars
      include_vars: vars.yml
      tags: always
  roles:
    - ivansible.lin_core
    - ivansible.lin_nginx
  tasks:
    - name: stop exim from taking port 25 on github runners
      systemd:
        name: exim4
        state: stopped
        masked: true
      become: true
      ignore_errors: true
...
