---
is_permitted: false
lin_use_ssh: false
lin_firewall: none
allow_sysctl: false
lin_core_time_sync: false
lin_core_system_locale: en_US.UTF-8
lin_systemd_tmpfiles: "{{ lookup('env','IVATEST_SYSTEMD_TMPFILES')|d('true',true)|bool }}"

cgpro_deb_url: https://dropbox.com/s/u4s7d3p7jnquvdx/CGatePro-Linux_6.2-7_amd64.deb?dl=1
...
