---
- name: verify
  hosts: all
  tasks:
    - name: vars
      include_vars: vars.yml
      tags: always

    - name: assert that cgpro service is started and enabled
      service_facts:
    - assert:
        that: ansible_facts.services['cgpro.service'].state == 'running'
    - assert:
        that: ansible_facts.services['cgpro.service'].status == 'enabled'

    - name: assert that mail site works
      command: >
        curl -ksL https://{{ host }}
          --resolve {{ host }}:443:{{ addr }}
          --resolve {{ host }}:80:{{ addr }}
      vars:
        host: mail.example.com
        addr: 127.0.0.1
      args:
        warn: false
      changed_when: false
      register: html_mail
    - assert:
        that: html_mail.stdout is search('Welcome to CommuniGate Pro,')

    - name: assert that admin site works
      command: >
        curl -ksL https://{{ host }}
          --resolve {{ host }}:443:{{ addr }}
          --resolve {{ host }}:80:{{ addr }}
      vars:
        host: cgpro.example.com
        addr: 127.0.0.1
      args:
        warn: false
      changed_when: false
      register: html_admin
    - assert:
        that: html_admin.stdout is search('Welcome to CommuniGate Pro Server Administration.')

    - name: assert that smtp port answers
      shell: nc -v -w1 localhost 25
      args:
        stdin: ""
        warn: false
      changed_when: false
      register: reply_smtp
    - assert:
        that: reply_smtp.stdout is search('ESMTP CommuniGate Pro')
...
