---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: localhost
    groups:
      - molecule
provisioner:
  name: ansible
  inventory:
    group_vars:
      molecule:
        lin_core_system_locale: en_US.UTF-8
        allow_sysctl: false
        lin_use_ssh: ${IVATEST_SSH_SERVER:-true}
        lin_systemd_tmpfiles: ${IVATEST_SYSTEMD_TMPFILES:-true}
        # these pass on host:
        lin_firewall: ${IVATEST_FIREWALL:-ferm}
        lin_core_time_sync: true
        # settings:
        cgpro_deb_url: https://dropbox.com/s/u4s7d3p7jnquvdx/CGatePro-Linux_6.2-7_amd64.deb?dl=1
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  lint:
    name: ansible-lint
verifier:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
scenario:
  name: localhost
  test_sequence:
    - lint
    - dependency
    - syntax
    - prepare
    - converge
    - idempotence
    - verify
...
