---
name: Molecule test
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

env:
  ROLE_NAME: ivansible.srv_cgpro
  ANSIBLE_FORCE_COLOR: true

jobs:
  localhost_test:
    name: test on host
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
    env:
      SCENARIO: localhost
      IVATEST_FIREWALL: ferm
      IVATEST_SSH_SERVER: false
      IVATEST_SYSTEMD_TMPFILES: false  # systemd-tmpfiles fails on github runner
      IVATEST_CHECK_HTTPS_HTML: false  # FIXME github runners have a listener on port 443 ?

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: ivansible/${{ env.ROLE_NAME }}

      - name: Install requisites
        shell: bash
        run: |
          # stock and pypy flavors of PyYAML are incompatible:
          sudo apt-get remove -q -y python3-yaml
          sudo -H pip3 install -U pip setuptools wheel
          sudo -H pip3 install docker jmespath boto3 mitogen molecule pytest testinfra
          # also pulled: ansible-lint yamllint flake8

      - name: Run test
        shell: bash
        run: cd ivansible/$ROLE_NAME && molecule test -s $SCENARIO
        # disable direct test on github runner with open ports 25/80/443
        if: false

  docker_test:
    name: tests in docker
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    env:
      SCENARIO: default
      IVATEST_FIREWALL: none
      IVATEST_SSH_SERVER: true
      IVATEST_SYSTEMD_TMPFILES: true
      IVATEST_CHECK_HTTPS_HTML: true

    steps:  # copy-pastng above steps since anchors are unsupported
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: ivansible/${{ env.ROLE_NAME }}

      - name: Install requisites
        shell: bash
        run: |
          # stock and pypy flavors of PyYAML are incompatible:
          sudo apt-get remove -q -y python3-yaml
          sudo -H pip3 install -U pip setuptools wheel
          sudo -H pip3 install docker jmespath boto3 mitogen molecule pytest testinfra
          # also pulled: ansible-lint yamllint flake8

      - name: Run test
        shell: bash
        run: cd ivansible/$ROLE_NAME && molecule test -s $SCENARIO
...
